# Generated by Django 5.2 on 2026-03-20 12:40

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_description', tinymce.models.HTMLField()),
                ('news_slugs', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='news_title', unique=True)),
            ],
        ),
    ]
