# Generated by Django 5.2 on 2026-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='news/'),
        ),
    ]
