# Generated by Django 5.2 on 2026-03-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('course_image', models.ImageField(upload_to='courses')),
                ('course_desc', models.CharField(max_length=250)),
            ],
        ),
    ]
