# Generated by Django 5.2 on 2026-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serice_image', models.CharField(max_length=50)),
                ('service_heading', models.CharField(max_length=50)),
                ('service_button', models.CharField(max_length=50)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
