# Generated by Django 5.2 on 2026-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='serice_icon',
            new_name='service_icon',
        ),
        migrations.RemoveField(
            model_name='services',
            name='serice_image',
        ),
        migrations.AddField(
            model_name='services',
            name='service_image',
            field=models.ImageField(default='events/default.jpg', upload_to='events/'),
            preserve_default=False,
        ),
    ]
