# Generated by Django 5.2 on 2026-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_serice_icon_service_service_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.CharField(max_length=50),
        ),
    ]
